// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmtShWWJa3Hn9EkgPcQBaDgIFmoR26mGg',
    appId: '1:466123461365:web:336c3f0427f2382ee1abbc',
    messagingSenderId: '466123461365',
    projectId: 'food-delivery-app-982fb',
    authDomain: 'food-delivery-app-982fb.firebaseapp.com',
    storageBucket: 'food-delivery-app-982fb.firebasestorage.app',
    measurementId: 'G-Y35Z9ZVG90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZtSMWoXqEhq9QOFulDOi4TJgm9YhFPI',
    appId: '1:466123461365:android:e244bdf0ef92dfd0e1abbc',
    messagingSenderId: '466123461365',
    projectId: 'food-delivery-app-982fb',
    storageBucket: 'food-delivery-app-982fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9h7bj66iDlwGmYxuCegBuzunq48issSo',
    appId: '1:466123461365:ios:c1e6384b1da387c1e1abbc',
    messagingSenderId: '466123461365',
    projectId: 'food-delivery-app-982fb',
    storageBucket: 'food-delivery-app-982fb.firebasestorage.app',
    iosClientId: '466123461365-ud2fde6i0l3l06uimkpdf5nkv4vqtb6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9h7bj66iDlwGmYxuCegBuzunq48issSo',
    appId: '1:466123461365:ios:c1e6384b1da387c1e1abbc',
    messagingSenderId: '466123461365',
    projectId: 'food-delivery-app-982fb',
    storageBucket: 'food-delivery-app-982fb.firebasestorage.app',
    iosClientId: '466123461365-ud2fde6i0l3l06uimkpdf5nkv4vqtb6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmtShWWJa3Hn9EkgPcQBaDgIFmoR26mGg',
    appId: '1:466123461365:web:45af75b723966ac0e1abbc',
    messagingSenderId: '466123461365',
    projectId: 'food-delivery-app-982fb',
    authDomain: 'food-delivery-app-982fb.firebaseapp.com',
    storageBucket: 'food-delivery-app-982fb.firebasestorage.app',
    measurementId: 'G-PW97NMXFQK',
  );
}
